services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    depends_on:
      - db
      - dynamodb
    environment:
      - M2_HOME=/root/.m2
      - POSTGRES_HOST=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=dspdemo
      - AWS_DYNAMODB_ENDPOINT=http://dynamodb:8000
    networks:
      - app
    ports:
      - 8080:8080
    volumes:
      - $HOME/.m2:/root/.m2
      - $HOME/.aws:/root/.aws:ro
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: db
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=dspdemo
    ports:
      - 5432:5432  # ← add this, maps container port to your machine
    networks:
      - app
    volumes:
      - dbdata:/var/lib/postgresql/data  # different path from MySQL
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - 8000:8000
    networks:
      - app
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory" ]
networks:
  app: {}

volumes:
  dbdata: {}