spring.application.name=dsp-demo-project
server.port=8080
app.endpoint.name=ConfDefName
app.endpoint.chapter-count=1919191
app.endpoint.ratings=0

logging.level.org.springframework.web=DEBUG
logging.level.com.example.dspdemoproject=INFO
logging.file.name=LogbackLoggingDev.log

# AWS RDS Connection Details
#spring.datasource.url=jdbc:postgresql://://amazonaws.com
spring.datasource.url=jdbc:postgresql://dsp-demo-1.cwomfw6wy9rv.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=verify-full&sslrootcert=./global-bundle.pem
spring.datasource.username=postgres
spring.datasource.password=Postgres2007!

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# only expose health and info publicly
#management.endpoints.web.exposure.include=health,info

# show full health details
management.endpoint.health.show-details=always

# optional: run actuator on a separate port
management.server.port=8081